apps/funcionarios/urls.py
from django.urls import path
from .views import (
    FuncionariosList,
    FuncionarioEdit,
    FuncionarioDelete,
    FuncionarioCreate,
    Pdf,
    PdfDebug
)

from.views import rel_HE_func_reportlab

urlpatterns = [
    path('', FuncionariosList.as_view(), name='list_funcionarios'),
    path('edit/<int:pk>/', FuncionarioEdit.as_view(), name='update_funcionario'),
    path('delete/<int:pk>/', FuncionarioDelete.as_view(), name='delete_funcionario'),
    path('Create/', FuncionarioCreate.as_view(), name='create_funcionario'),
    path('rel-HE-func-reportlab', rel_HE_func_reportlab, name='rel_he_func_reportlab'),
    path('rel-HE-func-emp-xlwt', Pdf.as_view(), name='rel_he_func_emp_xlwt'),
    path('rel-HE-func-emp-xlwt_debug', PdfDebug.as_view(), name='rel_he_func_emp_xlwt_debug'),
]

spwm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth import urls

    # DjangoRest
from rest_framework import routers
from apps.spwm_ws import views
from apps.funcionarios.api.views import FuncionarioViewSet
from apps.registro_hora_extra.api.views import RegistroHoraExtraViewSet



router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'api/funcionarios', FuncionarioViewSet)
router.register(r'api/banco-horas', RegistroHoraExtraViewSet)


urlpatterns = [
    path('', include('apps.spwm_ws.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('empresa/', include('apps.empresas.urls')),
    path('documentosfunc/', include('apps.documentosfunc.urls')),
    path('horas-extras/', include('apps.registro_hora_extra.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('login/', auth_views.LoginView.as_view(), name='login'),

    # DjangoRest
    path('', include(router.urls)),
    path('api-auth/', include(
        'rest_framework.urls', namespace='rest_framework'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
] + urlpatterns


admin.site.site_header = 'SPWM'
admin.site.index_title = 'SPWM - Administração'
admin.site.site_title = 'Seja bem vindo ao SPWM'

apps/documentosfunc/models.py
from django.db import models
from django.shortcuts import reverse

from apps.funcionarios.models import Funcionario
from apps.empresas.models import Empresa


class DocumentoFunc(models.Model):
    descricao = models.CharField(max_length=100)
    proprietariofunc = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentosfunc')

    def get_absolute_url(self):
        return reverse('update_funcionario', args=[self.proprietariofunc.id])

    def __str__(self):
        return self.descricao
    

apps/funcionarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from apps.departamentos.models import Departamento
from apps.empresas.models import Empresa
from django.db.models import Sum

from django.core.mail import send_mail, mail_admins, send_mass_mail
from django.template.loader import render_to_string

class Funcionario(models.Model):
    nome = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    cpf = models.CharField(max_length=100, null=False, blank=False)
    departamentos = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(
        Empresa, on_delete=models.PROTECT, null=True, blank=True)
    imagem = models.ImageField()
    de_ferias = models.BooleanField(default=False)


    def get_absolute_url(self):
        return reverse('list_funcionarios')


    @property
    def total_horas_extra(self):
        total = self.registrohoraextra_set.filter(
            utilizada=False).aggregate(
            Sum('horas'))['horas__sum']
        return total or 0


    def save(self, *args, **kwargs):
        super(Funcionario, self).save(*args, **kwargs)

        data = {'funcionario': self.nome}
        plain_text = render_to_string(
            'funcionarios/emails/novo_funcionario.txt', data)
        html_mail = render_to_string(
            'funcionarios/emails/novo_funcionario.html', data)
        
        send_mail(
            'Novo Funcionário Cadastrado no SPWM',
            plain_text,
            'nelson.freire@ativa-qs.com.br',
            ['nelson.freire@ativa-qs.com.br', 'nelson.freire@spwm.com.br'],
            html_message=html_mail,
            fail_silently=False
        )

        mail_admins(
            'Novo Funcionário Cadastrado',
            plain_text,

            html_message=html_mail,
            fail_silently=False
        )


        message1 = ('SPWM', 'Aproveite a promoção do SPWM', 'nelson.freire@spwm.com.br',
                    ['nelson.freire@ativa-qs.com.br',
                    'nelson.freire@spwm.com.br',
                    'wpativa01@outlook.com.br', ]
                    )
        message2 = ('SPWM', 'Aproveite a nova promoção do SPWM', 'nelson.freire@spwm.com.br',
        ['nelson.freire@ativa-qs.com.br',
         'nelson.freire@spwm.com.br',
         'wpativa01@outlook.com.br', ]
                    )
        send_mass_mail((message1, message2), fail_silently=False)

    def __str__(self):
        return self.nome

apps/registro_hora_extra/models.py
from django.db import models
from django.urls import reverse
from apps.funcionarios.models import Funcionario


class RegistroHoraExtra(models.Model):
    motivo = models.CharField(max_length=100)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    horas = models.DecimalField(max_digits=6, decimal_places=2)
    utilizada = models.BooleanField(default=False)


    def get_absolute_url(self):
        return reverse('update_funcionario', args=[self.funcionario.pk])


    def __str__(self):
        return self.motivo

apps/funcionarios/api/views.py
from rest_framework import viewsets
from apps.funcionarios.api.serializers import FuncionarioSerializer
from apps.funcionarios.models import Funcionario
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication


class FuncionarioViewSet(viewsets.ModelViewSet):
    queryset = Funcionario.objects.all()
    serializer_class = FuncionarioSerializer
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

apps/funcionarios/views.py
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from .models import Funcionario
from django.views.generic import (
    ListView,
    UpdateView,
    DeleteView,
    CreateView
)

import io
from django.http import FileResponse, HttpResponse
from reportlab.pdfgen import canvas
from django.utils.translation import gettext as _

from django.views.generic.base import View, TemplateView
from django.template.loader import get_template
import xhtml2pdf.pisa as pisa

class FuncionariosList(ListView):
    model = Funcionario

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['report_button'] = _("Employee report")
        return context

    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        return Funcionario.objects.filter(empresa=empresa_logada)


class FuncionarioEdit(UpdateView):
    model = Funcionario
    fields = ['nome', 'cpf', 'departamentos']


class FuncionarioDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('list_funcionarios')


class FuncionarioCreate(CreateView):
    model = Funcionario
    fields = ['nome', 'cpf', 'departamentos']

    def form_valid(self, form):
        funcionario = form.save(commit=False)
        username = funcionario.nome.split(' ')[0] + funcionario.nome.split(' ')[1]
        funcionario.empresa = self.request.user.funcionario.empresa
        funcionario.user = User.objects.create(username=username)
        funcionario.save()
        return super(FuncionarioCreate, self).form_valid(form)


def rel_HE_func_reportlab(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachement; filename="RelFunc001.pdf"'

    buffer = io.BytesIO()
    p = canvas.Canvas(buffer)




    funcionarios = Funcionario.objects.filter(empresa=request.user.funcionario.empresa)

    p.drawString(10, 810, "Relação de H.E. dos Funcionarios.")
    p.drawString(10, 790, '' * 87)

    str_ = 'Empresa: %s '
    p.drawString(10, 780, str_ % (request.user.funcionario.empresa))


    str_ = 'Nome: %s | Horas no Banco de Extra: %.2f'

    p.drawString(10, 770, '. ' * 87)
    p.drawString(10, 760, '' * 87)

    y = 750
    for funcionario in funcionarios:
        p.drawString(10, y, str_ % (funcionario.nome,
                    funcionario.total_horas_extra))
        y -= 20

    p.showPage()
    p.save()

    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)

    return response

#
# def rel_HE_func_emp_reportlab(request):
#     response = HttpResponse(content_type='application/pdf')
#     response['Content-Disposition'] = 'attachement; filename="RelFuncemp001.pdf"'
#
#     buffer = io.BytesIO()
#     p = canvas.Canvas(buffer)
#
#     p.drawString(10, 810, "Relação de H.E. dos Funcionarios.")
#
#     funcionarios = Funcionario.objects.all()
#
#
#     str_ = 'Empresa: %s >|Nome: %s | Hora Extra: %.2f'
#
#
#
#     p.drawString(10, 790, '. ' * 87)
#
#     y = 780
#     for funcionario in funcionarios:
#         p.drawString(10, y, str_ % (funcionario.empresa,
#             funcionario.nome, funcionario.total_horas_extras))
#         y -= 20
#
#     p.showPage()
#     p.save()
#
#     pdf = buffer.getvalue()
#     buffer.close()
#     response.write(pdf)
#
#     return response

class Render:
    @staticmethod
    def render(path: str, params: dict, filename: str):
        template = get_template(path)
        html = template.render(params)
        response = io.BytesIO()
        pdf = pisa.pisaDocument(
            io.BytesIO(html.encode("UTF-8")), response)
        if not pdf.err:
            response = HttpResponse(
                response.getvalue(), content_type='application/pdf')
            response['Content-Disposition'] = 'attachment;filename=%s.pdf' % filename
            return response
        else:
            return HttpResponse("Error Rendering PDF", status=400)

class Pdf(View):

    def get(self, request):
        params = {
            'today': 'variavel today',
            'sales': 'variavel sales',
            'request': request,
        }
        return Render.render('funcionarios/relatorio.html', params, 'myfile')


class PdfDebug(TemplateView):
    template_name = 'funcionarios/lista_funcionarios.html'

apps/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}


{% block main %}

<h2>Deletar Funcionário.</h2><br>

<form method="POST">

    {% csrf_token %}
    <h4>Tem certeza que quer deletar o Funcionário:{{ obj }}</h4><br><br>
    <h3>{{ funcionario.nome }}</h3>
    {{ form.as_p }}
<br><br>
    <button type="submit" class="btn btn-outline-danger btn-sm">Confirmar</button>
</form>

{% endblock %}

{% block static %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}

{% block main %}

    <h2>Cadastro do  Funcionário</h2>

<br>
<form method="POST">

    {% csrf_token %}

    {{ form|bootstrap }}

    <button type="submit" class="btn btn-outline-primary btn-sm">Salvar e voltar para a listagem</button>
</form>
<br>
{% if object %}
----------------------------------------------------------------
    <br>
    <h4>Lista de documentos do funcionario.</h4>

    <ol>
        {% for documentofunc in object.documentofunc_set.all %}
            <li>
                 <a href="{{ documentofunc.arquivo.url }}"> {{ documentofunc }}</a><br>
            </li>
        {% endfor %}
     <a href="{% url 'create_documento_func' object.id %}"
        class="btn btn-outline-success btn-sm">Adicionar  documento
     </a>

    </ol>

------------------------------------------------------------------
 <br>
    <h4>Banco de Horas.</h4>

    <h5>Total de horas extras não utilizadas: {{ object.total_horas_extra }}</h5>
    <ol>
        {% for registro_he_func in object.registrohoraextra_set.all %}
            <li>
                 <a href="{% url 'update_hora_extra' registro_he_func.pk %}">
                     {{ registro_he_func.motivo }} </a>| {{ registro_he_func.horas }}
                 <br>
            </li>
        {% endfor %}
    </ol>



{% endif %}
{% endblock %}

{% block static %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}


{% block main %}

<h2>Lista de Funcionários</h2>
<br>

    {% for funcionario in object_list %}
       <a href="{% url 'update_funcionario' funcionario.pk %}">
          {{ funcionario.pk }} - {{ funcionario }}
       </a>
       <a href="{% url 'delete_funcionario' funcionario.pk %}"
           >Deletar</a>
<br>
    {% endfor %}
<br>
     <a href="{% url 'create_funcionario' %}"
        class="btn btn-outline-primary btn-sm">Novo</a>

     <a href="{% url 'rel_he_func_reportlab' %}"
        class="btn btn-outline-primary btn-sm">{{ report_button }}</a>

    <a href="{% url 'rel_he_func_emp_xlwt' %}"
       class="btn btn-outline-primary btn-sm">Gerar Relatório xlwt</a>

    <a href="{% url 'rel_he_func_emp_xlwt_debug' %}"
       class="btn btn-outline-danger btn-sm">Gerar Relatório xlwtDebug</a><br>

{% endblock %}

{% block static %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

{% endblock %}

apps/funcionarios/templates/funcionarios/lista_funcionarios.html
{% extends 'base.html' %}
{% load bootstrap %}


{% block menu %}
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link " href="">Home</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle active" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Cadastros</a>
            <div class="dropdown-menu">
            <a class="dropdown-item  active" href="list_funcionarios">Funcionarios</a>
            <a class="dropdown-item" href="">Veiculos</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="">Marca</a>
            <a class="dropdown-item" href="">Parametros</a>
            </div>
        </li>    
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Planos de Serviços</a>
            <div class="dropdown-menu">
            <a class="dropdown-item" href="">Plano Rotativo</a>
            <a class="dropdown-item" href="">Plano Mensalista</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="">Movimento Rotativo</a>
            <a class="dropdown-item" href="">Movimento Mensalista</a>
            </div>
        </li>    

            <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
            <a class="nav-link disabled" href="#">Desativado</a>
            </li>
    </ul>

{% endblock %}


{% block main %}

<div class="row">
    <div class="col-12">
        <h1>Estacionamento ATIVA</h1><br>
    </div>
</div>

<div class="row">
    <div class="col-sm-4">
            <h2>Cadastro</h2><br>
            <h6>Preencha para cadastrar um novo Cliente</h6><br>

    </div>
    <div class="col-sm-8">
            <h2>Lista de Funcionarios</h2><br>
        <h6>Clique no ID para selecionar o Cliente</h6>
        <table class="table ">
            <table class="table table-sm table-striped table-hover">
                <thead class="thead-dark">
                    <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Endereço</th>
                    <th scope="col">Telefone</th>
                    </tr>
                </thead>
                <tbody>
                    {% for funcionario in funcionarios %}
                    <tr>
                    <th scope="row"><a href="{% url 'update_funcionario' funcionario.id %}">
                            {{ funcionario.id }}</a></th>
                    <td>{{ funcionario.nome }}</td>

                    </tr>
                    {% endfor %}
                </tbody>
             </table>
        </table>
        
    </div> 
</div>

{% endblock %}

apps/funcionarios/templates/funcionarios/relatorio.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}

{% block staticcss %}
    <style>
        .teste {
        color: red;
        }
    </style>

{% endblock %}



{% block main %}

    <h2 class="teste">Relatorio Cadastro do  Funcionário</h2>
    <h2>{{ sales }}</h2>
 <a href=""class="btn btn-outline-primary btn-sm">Criar Empresa</a><br>

{% endblock %}

{% block static %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

{% endblock %}